### ISSUE TITLE
what are constraints porting  this to windows?

### ISSUE THREAD

**Issue by plkumar** [octoblu/alljoyn#10]
i tried to install this on windows and it failed, i understand by looking at the .gyp file that it currently support only mac and Linux, before i start making the necessary changes, i just wanted to understand what are the constraints you foresee or aware of in making this work on windows.

**Comment by dodolzg** [comment]
Hi, plkumar, have you found the reason why it does not work on windows?

**Comment by plkumar** [comment]
Hi @dodolzg No I did not make much progress on this due other priorities, but as a work around, you may be able use the https://github.com/Microsoft/node-uwp on Window10 and explore using the windows10 built in Alljoyn capabilities in UWP.

**Comment by dodolzg** [comment]
@plkumar , Thanks, I will look into it
